### ISSUE TITLE
Finish support for annotated indexes

### ISSUE THREAD

**Issue by PeterKnego** [Spikeify/spikeify#1]
Add support for the following to the new annotated index building:
- Auto-detection of index type based on the field type
- Update tests using the deprecated index/query methods: QueryTest
- Update the wiki to the new way of creating indexes: https://github.com/Spikeify/spikeify/wiki/Queries

**Comment by drejc** [comment]
Added support for automatic index type and index collection type resolve according to field type.
Removed need to specify index collection type when filtering.
Removed deprecated Scanner methods.
Added manual index look up in case setName is explicit set on query.
